export const API_URL = "http://localhost:8082"
export const ADMIN_URL = "http://localhost:8083"
export const CDN_URL = "https://cdn.animefoda.top"
export const AUTH_URL = "http://localhost:8080"
export const USER_URL = "http://localhost:8083"
export const GATEWAY_URL = "http://localhost:8084"